/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 124
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 69
#define ALIAS_COUNT 0
#define TOKEN_COUNT 42
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 15
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_SPACE = 2,
  anon_sym_LF = 3,
  anon_sym_DOT = 4,
  anon_sym_static = 5,
  anon_sym_LBRACE = 6,
  anon_sym_RBRACE = 7,
  anon_sym_get = 8,
  anon_sym_SEMI = 9,
  anon_sym_set = 10,
  anon_sym_none = 11,
  anon_sym_private = 12,
  anon_sym_protectedandinternal = 13,
  anon_sym_protected = 14,
  anon_sym_internal = 15,
  anon_sym_protectedorinternal = 16,
  anon_sym_public = 17,
  anon_sym_DOTctor = 18,
  anon_sym_LPAREN = 19,
  anon_sym_RPAREN = 20,
  anon_sym_COMMA = 21,
  anon_sym_EQ = 22,
  anon_sym_enum = 23,
  anon_sym_LBRACK = 24,
  anon_sym_RBRACK = 25,
  anon_sym_LT = 26,
  anon_sym_GT = 27,
  sym_null_literal = 28,
  anon_sym_SQUOTE = 29,
  sym_character_literal_content = 30,
  anon_sym_DQUOTE = 31,
  aux_sym_string_literal_content_token1 = 32,
  aux_sym_string_literal_content_token2 = 33,
  sym_escape_sequence = 34,
  sym_integer_literal = 35,
  sym_real_literal = 36,
  anon_sym_DASH = 37,
  anon_sym_true = 38,
  anon_sym_false = 39,
  sym__commas = 40,
  sym__refs = 41,
  sym_source_file = 42,
  sym_definition = 43,
  sym_path = 44,
  sym_namespace_part = 45,
  sym_signature = 46,
  sym_property_signature = 47,
  sym_getter = 48,
  sym_setter = 49,
  sym_accessibility = 50,
  sym_method_signature = 51,
  sym_arg_list = 52,
  sym_arg = 53,
  sym_enum_signature = 54,
  sym_type_list = 55,
  sym_type = 56,
  aux_sym__array_modifier = 57,
  aux_sym__ref_modifier = 58,
  sym_generic_type = 59,
  sym_simple_type = 60,
  sym_default_value = 61,
  sym_char_literal = 62,
  sym_string_literal = 63,
  sym_string_literal_content = 64,
  sym_negative_literal = 65,
  sym_boolean_literal = 66,
  aux_sym_source_file_repeat1 = 67,
  aux_sym_string_literal_repeat1 = 68,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_SPACE] = " ",
  [anon_sym_LF] = "\n",
  [anon_sym_DOT] = ".",
  [anon_sym_static] = "static",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_get] = "get",
  [anon_sym_SEMI] = ";",
  [anon_sym_set] = "set",
  [anon_sym_none] = "none",
  [anon_sym_private] = "private",
  [anon_sym_protectedandinternal] = "protectedandinternal",
  [anon_sym_protected] = "protected",
  [anon_sym_internal] = "internal",
  [anon_sym_protectedorinternal] = "protectedorinternal",
  [anon_sym_public] = "public",
  [anon_sym_DOTctor] = ".ctor",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_EQ] = "=",
  [anon_sym_enum] = "enum",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [sym_null_literal] = "null_literal",
  [anon_sym_SQUOTE] = "'",
  [sym_character_literal_content] = "character_literal_content",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_content_token1] = "string_literal_content_token1",
  [aux_sym_string_literal_content_token2] = "string_literal_content_token2",
  [sym_escape_sequence] = "escape_sequence",
  [sym_integer_literal] = "integer_literal",
  [sym_real_literal] = "real_literal",
  [anon_sym_DASH] = "-",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym__commas] = "_commas",
  [sym__refs] = "_refs",
  [sym_source_file] = "source_file",
  [sym_definition] = "definition",
  [sym_path] = "path",
  [sym_namespace_part] = "namespace_part",
  [sym_signature] = "signature",
  [sym_property_signature] = "property_signature",
  [sym_getter] = "getter",
  [sym_setter] = "setter",
  [sym_accessibility] = "accessibility",
  [sym_method_signature] = "method_signature",
  [sym_arg_list] = "arg_list",
  [sym_arg] = "arg",
  [sym_enum_signature] = "enum_signature",
  [sym_type_list] = "type_list",
  [sym_type] = "type",
  [aux_sym__array_modifier] = "_array_modifier",
  [aux_sym__ref_modifier] = "_ref_modifier",
  [sym_generic_type] = "generic_type",
  [sym_simple_type] = "simple_type",
  [sym_default_value] = "default_value",
  [sym_char_literal] = "char_literal",
  [sym_string_literal] = "string_literal",
  [sym_string_literal_content] = "string_literal_content",
  [sym_negative_literal] = "negative_literal",
  [sym_boolean_literal] = "boolean_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_string_literal_repeat1] = "string_literal_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_static] = anon_sym_static,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_get] = anon_sym_get,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_set] = anon_sym_set,
  [anon_sym_none] = anon_sym_none,
  [anon_sym_private] = anon_sym_private,
  [anon_sym_protectedandinternal] = anon_sym_protectedandinternal,
  [anon_sym_protected] = anon_sym_protected,
  [anon_sym_internal] = anon_sym_internal,
  [anon_sym_protectedorinternal] = anon_sym_protectedorinternal,
  [anon_sym_public] = anon_sym_public,
  [anon_sym_DOTctor] = anon_sym_DOTctor,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [sym_null_literal] = sym_null_literal,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [sym_character_literal_content] = sym_character_literal_content,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_content_token1] = aux_sym_string_literal_content_token1,
  [aux_sym_string_literal_content_token2] = aux_sym_string_literal_content_token2,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_integer_literal] = sym_integer_literal,
  [sym_real_literal] = sym_real_literal,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym__commas] = sym__commas,
  [sym__refs] = sym__refs,
  [sym_source_file] = sym_source_file,
  [sym_definition] = sym_definition,
  [sym_path] = sym_path,
  [sym_namespace_part] = sym_namespace_part,
  [sym_signature] = sym_signature,
  [sym_property_signature] = sym_property_signature,
  [sym_getter] = sym_getter,
  [sym_setter] = sym_setter,
  [sym_accessibility] = sym_accessibility,
  [sym_method_signature] = sym_method_signature,
  [sym_arg_list] = sym_arg_list,
  [sym_arg] = sym_arg,
  [sym_enum_signature] = sym_enum_signature,
  [sym_type_list] = sym_type_list,
  [sym_type] = sym_type,
  [aux_sym__array_modifier] = aux_sym__array_modifier,
  [aux_sym__ref_modifier] = aux_sym__ref_modifier,
  [sym_generic_type] = sym_generic_type,
  [sym_simple_type] = sym_simple_type,
  [sym_default_value] = sym_default_value,
  [sym_char_literal] = sym_char_literal,
  [sym_string_literal] = sym_string_literal,
  [sym_string_literal_content] = sym_string_literal_content,
  [sym_negative_literal] = sym_negative_literal,
  [sym_boolean_literal] = sym_boolean_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_string_literal_repeat1] = aux_sym_string_literal_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_static] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_get] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_set] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_none] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_private] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_protectedandinternal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_protected] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_internal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_protectedorinternal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_public] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOTctor] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_null_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_character_literal_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_content_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_content_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_real_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym__commas] = {
    .visible = false,
    .named = true,
  },
  [sym__refs] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym_namespace_part] = {
    .visible = true,
    .named = true,
  },
  [sym_signature] = {
    .visible = true,
    .named = true,
  },
  [sym_property_signature] = {
    .visible = true,
    .named = true,
  },
  [sym_getter] = {
    .visible = true,
    .named = true,
  },
  [sym_setter] = {
    .visible = true,
    .named = true,
  },
  [sym_accessibility] = {
    .visible = true,
    .named = true,
  },
  [sym_method_signature] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_list] = {
    .visible = true,
    .named = true,
  },
  [sym_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_signature] = {
    .visible = true,
    .named = true,
  },
  [sym_type_list] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__array_modifier] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__ref_modifier] = {
    .visible = false,
    .named = false,
  },
  [sym_generic_type] = {
    .visible = true,
    .named = true,
  },
  [sym_simple_type] = {
    .visible = true,
    .named = true,
  },
  [sym_default_value] = {
    .visible = true,
    .named = true,
  },
  [sym_char_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal_content] = {
    .visible = true,
    .named = true,
  },
  [sym_negative_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arg_name = 1,
  field_arg_type = 2,
  field_class = 3,
  field_enum = 4,
  field_field = 5,
  field_name = 6,
  field_namespace = 7,
  field_parameters = 8,
  field_return_type = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arg_name] = "arg_name",
  [field_arg_type] = "arg_type",
  [field_class] = "class",
  [field_enum] = "enum",
  [field_field] = "field",
  [field_name] = "name",
  [field_namespace] = "namespace",
  [field_parameters] = "parameters",
  [field_return_type] = "return_type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 2},
  [4] = {.index = 6, .length = 2},
  [5] = {.index = 8, .length = 3},
  [6] = {.index = 11, .length = 2},
  [7] = {.index = 13, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_class, 2},
    {field_namespace, 0},
  [2] =
    {field_enum, 2},
    {field_field, 4},
  [4] =
    {field_name, 4},
    {field_return_type, 2},
  [6] =
    {field_name, 6},
    {field_return_type, 4},
  [8] =
    {field_name, 4},
    {field_parameters, 6},
    {field_return_type, 2},
  [11] =
    {field_arg_name, 2},
    {field_arg_type, 0},
  [13] =
    {field_name, 6},
    {field_parameters, 8},
    {field_return_type, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(26);
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead == '\r') SKIP(24);
      if (lookahead == ' ') ADVANCE(27);
      if (lookahead == '"') ADVANCE(45);
      if (lookahead == '\'') ADVANCE(43);
      if (lookahead == '(') ADVANCE(34);
      if (lookahead == ')') ADVANCE(35);
      if (lookahead == ',') ADVANCE(37);
      if (lookahead == '-') ADVANCE(69);
      if (lookahead == '.') ADVANCE(29);
      if (lookahead == '0') ADVANCE(57);
      if (lookahead == ';') ADVANCE(32);
      if (lookahead == '<') ADVANCE(41);
      if (lookahead == '=') ADVANCE(38);
      if (lookahead == '>') ADVANCE(42);
      if (lookahead == '[') ADVANCE(39);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == ']') ADVANCE(40);
      if (lookahead == '{') ADVANCE(30);
      if (lookahead == '}') ADVANCE(31);
      if (('&' <= lookahead && lookahead <= '*')) ADVANCE(78);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(58);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 1:
      if (lookahead == '\r') SKIP(1);
      if (lookahead == '"') ADVANCE(45);
      if (lookahead == '\'') ADVANCE(43);
      if (lookahead == ',') ADVANCE(77);
      if (lookahead == '-') ADVANCE(69);
      if (lookahead == '.') ADVANCE(12);
      if (lookahead == '0') ADVANCE(55);
      if (lookahead == ']') ADVANCE(40);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(56);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 2:
      if (lookahead == '\r') ADVANCE(46);
      if (lookahead == '"') ADVANCE(45);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(47);
      END_STATE();
    case 3:
      if (lookahead == '\r') ADVANCE(44);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(44);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        'U', 51,
        'u', 50,
        'x', 49,
        '"', 52,
        '\'', 52,
        '0', 52,
        '?', 52,
        '\\', 52,
        'a', 52,
        'b', 52,
        'e', 52,
        'f', 52,
        'n', 52,
        'r', 52,
        't', 52,
        'v', 52,
      );
      if (lookahead != 0) ADVANCE(48);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        'U', 23,
        'u', 19,
        'x', 16,
        '"', 52,
        '\'', 52,
        '0', 52,
        '?', 52,
        '\\', 52,
        'a', 52,
        'b', 52,
        'e', 52,
        'f', 52,
        'n', 52,
        'r', 52,
        't', 52,
        'v', 52,
      );
      END_STATE();
    case 6:
      if (lookahead == '_') ADVANCE(6);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      END_STATE();
    case 7:
      if (lookahead == 'c') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 9:
      if (lookahead == 'r') ADVANCE(33);
      END_STATE();
    case 10:
      if (lookahead == 't') ADVANCE(8);
      END_STATE();
    case 11:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(67);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(67);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(52);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(54);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(15);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(14);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(17);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(18);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      END_STATE();
    case 24:
      if (eof) ADVANCE(26);
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead == '\r') SKIP(24);
      if (lookahead == ' ') ADVANCE(27);
      if (lookahead == '"') ADVANCE(45);
      if (lookahead == '\'') ADVANCE(43);
      if (lookahead == '(') ADVANCE(34);
      if (lookahead == ')') ADVANCE(35);
      if (lookahead == ',') ADVANCE(37);
      if (lookahead == '-') ADVANCE(69);
      if (lookahead == '.') ADVANCE(29);
      if (lookahead == '0') ADVANCE(57);
      if (lookahead == ';') ADVANCE(32);
      if (lookahead == '<') ADVANCE(41);
      if (lookahead == '=') ADVANCE(38);
      if (lookahead == '>') ADVANCE(42);
      if (lookahead == '[') ADVANCE(39);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead == ']') ADVANCE(40);
      if (lookahead == '{') ADVANCE(30);
      if (lookahead == '}') ADVANCE(31);
      if (('&' <= lookahead && lookahead <= '*')) ADVANCE(78);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(58);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 25:
      if (eof) ADVANCE(26);
      if (lookahead == '\n') ADVANCE(28);
      if (lookahead == '\r') SKIP(25);
      if (lookahead == ' ') ADVANCE(27);
      if (lookahead == ')') ADVANCE(35);
      if (lookahead == ',') ADVANCE(36);
      if (lookahead == '.') ADVANCE(7);
      if (lookahead == '<') ADVANCE(41);
      if (lookahead == '>') ADVANCE(42);
      if (lookahead == '[') ADVANCE(39);
      if (lookahead == '}') ADVANCE(31);
      if (lookahead == '&' ||
          lookahead == '*') ADVANCE(78);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_SPACE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DOTctor);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_COMMA);
      if (lookahead == ',') ADVANCE(77);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_character_literal_content);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_string_literal_content_token1);
      if (lookahead == '\r') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_string_literal_content_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_string_literal_content_token2);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_string_literal_content_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(15);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_string_literal_content_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(18);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_string_literal_content_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(52);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(53);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_integer_literal);
      ADVANCE_MAP(
        '.', 12,
        '_', 74,
        'B', 72,
        'b', 72,
        'E', 70,
        'e', 70,
        'L', 62,
        'l', 62,
        'U', 61,
        'u', 61,
        'X', 73,
        'x', 73,
        'D', 68,
        'F', 68,
        'M', 68,
        'd', 68,
        'f', 68,
        'm', 68,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_integer_literal);
      ADVANCE_MAP(
        '.', 12,
        '_', 74,
        'E', 70,
        'e', 70,
        'L', 62,
        'l', 62,
        'U', 61,
        'u', 61,
        'D', 68,
        'F', 68,
        'M', 68,
        'd', 68,
        'f', 68,
        'm', 68,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_integer_literal);
      ADVANCE_MAP(
        '_', 71,
        'B', 72,
        'b', 72,
        'L', 62,
        'l', 62,
        'U', 61,
        'u', 61,
        'X', 73,
        'x', 73,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '_') ADVANCE(71);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(62);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '_') ADVANCE(72);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(62);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(61);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(59);
      if (lookahead == '-' ||
          ('2' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '_') ADVANCE(73);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(62);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(60);
      if (lookahead == '-' ||
          ('G' <= lookahead && lookahead <= 'Z') ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(63);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(63);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_real_literal);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_real_literal);
      ADVANCE_MAP(
        '_', 6,
        'E', 11,
        'e', 11,
        'D', 64,
        'F', 64,
        'M', 64,
        'd', 64,
        'f', 64,
        'm', 64,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_real_literal);
      if (lookahead == 'D' ||
          lookahead == 'F' ||
          lookahead == 'M' ||
          lookahead == 'd' ||
          lookahead == 'f' ||
          lookahead == 'm') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(66);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_real_literal);
      if (lookahead == 'D' ||
          lookahead == 'F' ||
          lookahead == 'M' ||
          lookahead == 'd' ||
          lookahead == 'f' ||
          lookahead == 'm') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_real_literal);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '+') ADVANCE(13);
      if (lookahead == '-') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(58);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(72);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(59);
      if (lookahead == '-' ||
          ('2' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(73);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(60);
      if (lookahead == '-' ||
          ('G' <= lookahead && lookahead <= 'Z') ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(66);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym__commas);
      if (lookahead == ',') ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym__refs);
      if (lookahead == '&' ||
          lookahead == '*') ADVANCE(78);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == '\r') SKIP(0);
      if (lookahead == 'e') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'g') ADVANCE(3);
      if (lookahead == 'i') ADVANCE(4);
      if (lookahead == 'n') ADVANCE(5);
      if (lookahead == 'p') ADVANCE(6);
      if (lookahead == 's') ADVANCE(7);
      if (lookahead == 't') ADVANCE(8);
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(10);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 4:
      if (lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 5:
      if (lookahead == 'o') ADVANCE(13);
      if (lookahead == 'u') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == 'r') ADVANCE(15);
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(17);
      if (lookahead == 't') ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 9:
      if (lookahead == 'u') ADVANCE(20);
      END_STATE();
    case 10:
      if (lookahead == 'l') ADVANCE(21);
      END_STATE();
    case 11:
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 12:
      if (lookahead == 't') ADVANCE(23);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(24);
      END_STATE();
    case 14:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 15:
      if (lookahead == 'i') ADVANCE(26);
      if (lookahead == 'o') ADVANCE(27);
      END_STATE();
    case 16:
      if (lookahead == 'b') ADVANCE(28);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 18:
      if (lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 19:
      if (lookahead == 'u') ADVANCE(31);
      END_STATE();
    case 20:
      if (lookahead == 'm') ADVANCE(32);
      END_STATE();
    case 21:
      if (lookahead == 's') ADVANCE(33);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_get);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(34);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(35);
      END_STATE();
    case 25:
      if (lookahead == 'l') ADVANCE(36);
      END_STATE();
    case 26:
      if (lookahead == 'v') ADVANCE(37);
      END_STATE();
    case 27:
      if (lookahead == 't') ADVANCE(38);
      END_STATE();
    case 28:
      if (lookahead == 'l') ADVANCE(39);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_set);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(40);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(41);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(43);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_none);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_null_literal);
      END_STATE();
    case 37:
      if (lookahead == 'a') ADVANCE(44);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 39:
      if (lookahead == 'i') ADVANCE(46);
      END_STATE();
    case 40:
      if (lookahead == 'i') ADVANCE(47);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 43:
      if (lookahead == 'n') ADVANCE(48);
      END_STATE();
    case 44:
      if (lookahead == 't') ADVANCE(49);
      END_STATE();
    case 45:
      if (lookahead == 'c') ADVANCE(50);
      END_STATE();
    case 46:
      if (lookahead == 'c') ADVANCE(51);
      END_STATE();
    case 47:
      if (lookahead == 'c') ADVANCE(52);
      END_STATE();
    case 48:
      if (lookahead == 'a') ADVANCE(53);
      END_STATE();
    case 49:
      if (lookahead == 'e') ADVANCE(54);
      END_STATE();
    case 50:
      if (lookahead == 't') ADVANCE(55);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_public);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_static);
      END_STATE();
    case 53:
      if (lookahead == 'l') ADVANCE(56);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_private);
      END_STATE();
    case 55:
      if (lookahead == 'e') ADVANCE(57);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_internal);
      END_STATE();
    case 57:
      if (lookahead == 'd') ADVANCE(58);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_protected);
      if (lookahead == 'a') ADVANCE(59);
      if (lookahead == 'o') ADVANCE(60);
      END_STATE();
    case 59:
      if (lookahead == 'n') ADVANCE(61);
      END_STATE();
    case 60:
      if (lookahead == 'r') ADVANCE(62);
      END_STATE();
    case 61:
      if (lookahead == 'd') ADVANCE(63);
      END_STATE();
    case 62:
      if (lookahead == 'i') ADVANCE(64);
      END_STATE();
    case 63:
      if (lookahead == 'i') ADVANCE(65);
      END_STATE();
    case 64:
      if (lookahead == 'n') ADVANCE(66);
      END_STATE();
    case 65:
      if (lookahead == 'n') ADVANCE(67);
      END_STATE();
    case 66:
      if (lookahead == 't') ADVANCE(68);
      END_STATE();
    case 67:
      if (lookahead == 't') ADVANCE(69);
      END_STATE();
    case 68:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 69:
      if (lookahead == 'e') ADVANCE(71);
      END_STATE();
    case 70:
      if (lookahead == 'r') ADVANCE(72);
      END_STATE();
    case 71:
      if (lookahead == 'r') ADVANCE(73);
      END_STATE();
    case 72:
      if (lookahead == 'n') ADVANCE(74);
      END_STATE();
    case 73:
      if (lookahead == 'n') ADVANCE(75);
      END_STATE();
    case 74:
      if (lookahead == 'a') ADVANCE(76);
      END_STATE();
    case 75:
      if (lookahead == 'a') ADVANCE(77);
      END_STATE();
    case 76:
      if (lookahead == 'l') ADVANCE(78);
      END_STATE();
    case 77:
      if (lookahead == 'l') ADVANCE(79);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_protectedorinternal);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(anon_sym_protectedandinternal);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 25},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 25},
  [5] = {.lex_state = 25},
  [6] = {.lex_state = 25},
  [7] = {.lex_state = 25},
  [8] = {.lex_state = 25},
  [9] = {.lex_state = 25},
  [10] = {.lex_state = 25},
  [11] = {.lex_state = 25},
  [12] = {.lex_state = 25},
  [13] = {.lex_state = 25},
  [14] = {.lex_state = 25},
  [15] = {.lex_state = 25},
  [16] = {.lex_state = 25},
  [17] = {.lex_state = 25},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 25},
  [22] = {.lex_state = 25},
  [23] = {.lex_state = 25},
  [24] = {.lex_state = 25},
  [25] = {.lex_state = 25},
  [26] = {.lex_state = 25},
  [27] = {.lex_state = 25},
  [28] = {.lex_state = 25},
  [29] = {.lex_state = 25},
  [30] = {.lex_state = 25},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 25},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 25},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 25},
  [37] = {.lex_state = 25},
  [38] = {.lex_state = 25},
  [39] = {.lex_state = 25},
  [40] = {.lex_state = 25},
  [41] = {.lex_state = 25},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 25},
  [44] = {.lex_state = 25},
  [45] = {.lex_state = 25},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 25},
  [48] = {.lex_state = 25},
  [49] = {.lex_state = 25},
  [50] = {.lex_state = 25},
  [51] = {.lex_state = 25},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 25},
  [56] = {.lex_state = 25},
  [57] = {.lex_state = 25},
  [58] = {.lex_state = 25},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 25},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 25},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 25},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 25},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 0},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 25},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_SPACE] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_static] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_get] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_set] = ACTIONS(1),
    [anon_sym_none] = ACTIONS(1),
    [anon_sym_private] = ACTIONS(1),
    [anon_sym_protectedandinternal] = ACTIONS(1),
    [anon_sym_protected] = ACTIONS(1),
    [anon_sym_internal] = ACTIONS(1),
    [anon_sym_protectedorinternal] = ACTIONS(1),
    [anon_sym_public] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym_null_literal] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [aux_sym_string_literal_content_token2] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym__commas] = ACTIONS(1),
    [sym__refs] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(64),
    [sym_definition] = STATE(14),
    [sym_path] = STATE(75),
    [sym_namespace_part] = STATE(69),
    [aux_sym_source_file_repeat1] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(9), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      anon_sym_DASH,
    STATE(71), 1,
      sym_default_value,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(7), 4,
      sym_null_literal,
      sym_integer_literal,
      sym_real_literal,
      sym_identifier,
    STATE(34), 4,
      sym_char_literal,
      sym_string_literal,
      sym_negative_literal,
      sym_boolean_literal,
  [29] = 7,
    ACTIONS(9), 1,
      anon_sym_SQUOTE,
    ACTIONS(11), 1,
      anon_sym_DQUOTE,
    ACTIONS(13), 1,
      anon_sym_DASH,
    STATE(43), 1,
      sym_default_value,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(7), 4,
      sym_null_literal,
      sym_integer_literal,
      sym_real_literal,
      sym_identifier,
    STATE(34), 4,
      sym_char_literal,
      sym_string_literal,
      sym_negative_literal,
      sym_boolean_literal,
  [58] = 6,
    ACTIONS(19), 1,
      anon_sym_protected,
    ACTIONS(21), 1,
      anon_sym_enum,
    STATE(65), 1,
      sym_accessibility,
    STATE(95), 1,
      sym_signature,
    STATE(88), 3,
      sym_property_signature,
      sym_method_signature,
      sym_enum_signature,
    ACTIONS(17), 6,
      anon_sym_none,
      anon_sym_private,
      anon_sym_protectedandinternal,
      anon_sym_internal,
      anon_sym_protectedorinternal,
      anon_sym_public,
  [84] = 8,
    ACTIONS(19), 1,
      anon_sym_protected,
    ACTIONS(23), 1,
      anon_sym_RBRACE,
    ACTIONS(25), 1,
      anon_sym_get,
    ACTIONS(27), 1,
      anon_sym_set,
    STATE(80), 1,
      sym_getter,
    STATE(81), 1,
      sym_setter,
    STATE(82), 1,
      sym_accessibility,
    ACTIONS(17), 6,
      anon_sym_none,
      anon_sym_private,
      anon_sym_protectedandinternal,
      anon_sym_internal,
      anon_sym_protectedorinternal,
      anon_sym_public,
  [114] = 8,
    ACTIONS(19), 1,
      anon_sym_protected,
    ACTIONS(25), 1,
      anon_sym_get,
    ACTIONS(27), 1,
      anon_sym_set,
    ACTIONS(29), 1,
      anon_sym_RBRACE,
    STATE(82), 1,
      sym_accessibility,
    STATE(102), 1,
      sym_getter,
    STATE(103), 1,
      sym_setter,
    ACTIONS(17), 6,
      anon_sym_none,
      anon_sym_private,
      anon_sym_protectedandinternal,
      anon_sym_internal,
      anon_sym_protectedorinternal,
      anon_sym_public,
  [144] = 6,
    ACTIONS(19), 1,
      anon_sym_protected,
    ACTIONS(27), 1,
      anon_sym_set,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
    STATE(106), 1,
      sym_setter,
    STATE(107), 1,
      sym_accessibility,
    ACTIONS(17), 6,
      anon_sym_none,
      anon_sym_private,
      anon_sym_protectedandinternal,
      anon_sym_internal,
      anon_sym_protectedorinternal,
      anon_sym_public,
  [168] = 6,
    ACTIONS(19), 1,
      anon_sym_protected,
    ACTIONS(27), 1,
      anon_sym_set,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    STATE(107), 1,
      sym_accessibility,
    STATE(118), 1,
      sym_setter,
    ACTIONS(17), 6,
      anon_sym_none,
      anon_sym_private,
      anon_sym_protectedandinternal,
      anon_sym_internal,
      anon_sym_protectedorinternal,
      anon_sym_public,
  [192] = 6,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(39), 1,
      anon_sym_LT,
    ACTIONS(41), 1,
      sym__refs,
    STATE(13), 1,
      aux_sym__array_modifier,
    STATE(28), 1,
      aux_sym__ref_modifier,
    ACTIONS(35), 3,
      anon_sym_SPACE,
      anon_sym_COMMA,
      anon_sym_GT,
  [213] = 7,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(45), 1,
      anon_sym_RPAREN,
    STATE(9), 1,
      sym_simple_type,
    STATE(12), 1,
      sym_generic_type,
    STATE(49), 1,
      sym_arg_list,
    STATE(50), 1,
      sym_arg,
    STATE(97), 1,
      sym_type,
  [235] = 7,
    ACTIONS(43), 1,
      sym_identifier,
    ACTIONS(47), 1,
      anon_sym_RPAREN,
    STATE(9), 1,
      sym_simple_type,
    STATE(12), 1,
      sym_generic_type,
    STATE(50), 1,
      sym_arg,
    STATE(57), 1,
      sym_arg_list,
    STATE(97), 1,
      sym_type,
  [257] = 5,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(41), 1,
      sym__refs,
    STATE(13), 1,
      aux_sym__array_modifier,
    STATE(28), 1,
      aux_sym__ref_modifier,
    ACTIONS(35), 3,
      anon_sym_SPACE,
      anon_sym_COMMA,
      anon_sym_GT,
  [275] = 5,
    ACTIONS(37), 1,
      anon_sym_LBRACK,
    ACTIONS(51), 1,
      sym__refs,
    STATE(15), 1,
      aux_sym__array_modifier,
    STATE(22), 1,
      aux_sym__ref_modifier,
    ACTIONS(49), 3,
      anon_sym_SPACE,
      anon_sym_COMMA,
      anon_sym_GT,
  [293] = 5,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(53), 1,
      ts_builtin_sym_end,
    STATE(69), 1,
      sym_namespace_part,
    STATE(75), 1,
      sym_path,
    STATE(17), 2,
      sym_definition,
      aux_sym_source_file_repeat1,
  [310] = 3,
    ACTIONS(57), 1,
      anon_sym_LBRACK,
    STATE(15), 1,
      aux_sym__array_modifier,
    ACTIONS(55), 4,
      anon_sym_SPACE,
      anon_sym_COMMA,
      anon_sym_GT,
      sym__refs,
  [323] = 1,
    ACTIONS(60), 6,
      anon_sym_SPACE,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_LT,
      anon_sym_GT,
      sym__refs,
  [332] = 5,
    ACTIONS(62), 1,
      ts_builtin_sym_end,
    ACTIONS(64), 1,
      sym_identifier,
    STATE(69), 1,
      sym_namespace_part,
    STATE(75), 1,
      sym_path,
    STATE(17), 2,
      sym_definition,
      aux_sym_source_file_repeat1,
  [349] = 5,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(69), 1,
      aux_sym_string_literal_content_token1,
    ACTIONS(71), 1,
      aux_sym_string_literal_content_token2,
    ACTIONS(73), 1,
      sym_escape_sequence,
    STATE(20), 2,
      sym_string_literal_content,
      aux_sym_string_literal_repeat1,
  [366] = 5,
    ACTIONS(69), 1,
      aux_sym_string_literal_content_token1,
    ACTIONS(71), 1,
      aux_sym_string_literal_content_token2,
    ACTIONS(75), 1,
      anon_sym_DQUOTE,
    ACTIONS(77), 1,
      sym_escape_sequence,
    STATE(18), 2,
      sym_string_literal_content,
      aux_sym_string_literal_repeat1,
  [383] = 5,
    ACTIONS(79), 1,
      anon_sym_DQUOTE,
    ACTIONS(81), 1,
      aux_sym_string_literal_content_token1,
    ACTIONS(84), 1,
      aux_sym_string_literal_content_token2,
    ACTIONS(87), 1,
      sym_escape_sequence,
    STATE(20), 2,
      sym_string_literal_content,
      aux_sym_string_literal_repeat1,
  [400] = 1,
    ACTIONS(55), 5,
      anon_sym_SPACE,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_GT,
      sym__refs,
  [408] = 3,
    ACTIONS(92), 1,
      sym__refs,
    STATE(23), 1,
      aux_sym__ref_modifier,
    ACTIONS(90), 3,
      anon_sym_SPACE,
      anon_sym_COMMA,
      anon_sym_GT,
  [420] = 3,
    ACTIONS(96), 1,
      sym__refs,
    STATE(23), 1,
      aux_sym__ref_modifier,
    ACTIONS(94), 3,
      anon_sym_SPACE,
      anon_sym_COMMA,
      anon_sym_GT,
  [432] = 5,
    ACTIONS(99), 1,
      sym_identifier,
    ACTIONS(101), 1,
      anon_sym_static,
    STATE(9), 1,
      sym_simple_type,
    STATE(12), 1,
      sym_generic_type,
    STATE(115), 1,
      sym_type,
  [448] = 1,
    ACTIONS(103), 5,
      anon_sym_SPACE,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_GT,
      sym__refs,
  [456] = 1,
    ACTIONS(105), 5,
      anon_sym_SPACE,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_GT,
      sym__refs,
  [464] = 5,
    ACTIONS(43), 1,
      sym_identifier,
    STATE(9), 1,
      sym_simple_type,
    STATE(12), 1,
      sym_generic_type,
    STATE(56), 1,
      sym_arg,
    STATE(97), 1,
      sym_type,
  [480] = 3,
    ACTIONS(92), 1,
      sym__refs,
    STATE(23), 1,
      aux_sym__ref_modifier,
    ACTIONS(49), 3,
      anon_sym_SPACE,
      anon_sym_COMMA,
      anon_sym_GT,
  [492] = 5,
    ACTIONS(43), 1,
      sym_identifier,
    STATE(9), 1,
      sym_simple_type,
    STATE(12), 1,
      sym_generic_type,
    STATE(44), 1,
      sym_type_list,
    STATE(45), 1,
      sym_type,
  [508] = 4,
    ACTIONS(43), 1,
      sym_identifier,
    STATE(9), 1,
      sym_simple_type,
    STATE(12), 1,
      sym_generic_type,
    STATE(51), 1,
      sym_type,
  [521] = 2,
    ACTIONS(109), 1,
      aux_sym_string_literal_content_token1,
    ACTIONS(107), 3,
      anon_sym_DQUOTE,
      aux_sym_string_literal_content_token2,
      sym_escape_sequence,
  [530] = 4,
    ACTIONS(43), 1,
      sym_identifier,
    STATE(9), 1,
      sym_simple_type,
    STATE(12), 1,
      sym_generic_type,
    STATE(110), 1,
      sym_type,
  [543] = 2,
    ACTIONS(109), 1,
      aux_sym_string_literal_content_token1,
    ACTIONS(107), 3,
      anon_sym_DQUOTE,
      aux_sym_string_literal_content_token2,
      sym_escape_sequence,
  [552] = 1,
    ACTIONS(111), 3,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [558] = 3,
    ACTIONS(113), 1,
      anon_sym_SPACE,
    ACTIONS(115), 1,
      anon_sym_LF,
    ACTIONS(117), 1,
      anon_sym_LPAREN,
  [568] = 1,
    ACTIONS(119), 3,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [574] = 1,
    ACTIONS(121), 3,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [580] = 2,
    ACTIONS(123), 1,
      anon_sym_SPACE,
    ACTIONS(125), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [588] = 1,
    ACTIONS(127), 3,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [594] = 1,
    ACTIONS(129), 3,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [600] = 1,
    ACTIONS(131), 3,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [606] = 3,
    ACTIONS(133), 1,
      anon_sym_SPACE,
    ACTIONS(135), 1,
      anon_sym_LF,
    ACTIONS(137), 1,
      anon_sym_LPAREN,
  [616] = 1,
    ACTIONS(139), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [621] = 2,
    ACTIONS(141), 1,
      anon_sym_COMMA,
    ACTIONS(143), 1,
      anon_sym_GT,
  [628] = 1,
    ACTIONS(145), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [633] = 2,
    ACTIONS(147), 1,
      anon_sym_SPACE,
    ACTIONS(149), 1,
      anon_sym_DOT,
  [640] = 2,
    ACTIONS(151), 1,
      sym_identifier,
    ACTIONS(153), 1,
      anon_sym_DOTctor,
  [647] = 1,
    ACTIONS(155), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [652] = 2,
    ACTIONS(157), 1,
      anon_sym_RPAREN,
    ACTIONS(159), 1,
      anon_sym_COMMA,
  [659] = 1,
    ACTIONS(161), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [664] = 1,
    ACTIONS(163), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [669] = 2,
    ACTIONS(165), 1,
      sym_character_literal_content,
    ACTIONS(167), 1,
      sym_escape_sequence,
  [676] = 2,
    ACTIONS(169), 1,
      sym_integer_literal,
    ACTIONS(171), 1,
      sym_real_literal,
  [683] = 2,
    ACTIONS(173), 1,
      anon_sym_RBRACK,
    ACTIONS(175), 1,
      sym__commas,
  [690] = 2,
    ACTIONS(177), 1,
      sym_identifier,
    ACTIONS(179), 1,
      anon_sym_DOTctor,
  [697] = 1,
    ACTIONS(181), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [702] = 2,
    ACTIONS(159), 1,
      anon_sym_COMMA,
    ACTIONS(183), 1,
      anon_sym_RPAREN,
  [709] = 2,
    ACTIONS(185), 1,
      anon_sym_get,
    ACTIONS(187), 1,
      anon_sym_set,
  [716] = 2,
    ACTIONS(189), 1,
      anon_sym_SPACE,
    ACTIONS(191), 1,
      anon_sym_LF,
  [723] = 1,
    ACTIONS(193), 1,
      anon_sym_SPACE,
  [727] = 1,
    ACTIONS(195), 1,
      anon_sym_LF,
  [731] = 1,
    ACTIONS(197), 1,
      anon_sym_SPACE,
  [735] = 1,
    ACTIONS(199), 1,
      sym_identifier,
  [739] = 1,
    ACTIONS(201), 1,
      ts_builtin_sym_end,
  [743] = 1,
    ACTIONS(203), 1,
      anon_sym_SPACE,
  [747] = 1,
    ACTIONS(205), 1,
      sym_identifier,
  [751] = 1,
    ACTIONS(207), 1,
      anon_sym_LBRACE,
  [755] = 1,
    ACTIONS(209), 1,
      sym_identifier,
  [759] = 1,
    ACTIONS(211), 1,
      anon_sym_DOT,
  [763] = 1,
    ACTIONS(213), 1,
      anon_sym_SPACE,
  [767] = 1,
    ACTIONS(215), 1,
      anon_sym_LF,
  [771] = 1,
    ACTIONS(217), 1,
      anon_sym_LF,
  [775] = 1,
    ACTIONS(219), 1,
      anon_sym_DOT,
  [779] = 1,
    ACTIONS(221), 1,
      anon_sym_SPACE,
  [783] = 1,
    ACTIONS(223), 1,
      anon_sym_SPACE,
  [787] = 1,
    ACTIONS(225), 1,
      anon_sym_SPACE,
  [791] = 1,
    ACTIONS(227), 1,
      anon_sym_LF,
  [795] = 1,
    ACTIONS(229), 1,
      anon_sym_SEMI,
  [799] = 1,
    ACTIONS(231), 1,
      anon_sym_SEMI,
  [803] = 1,
    ACTIONS(233), 1,
      anon_sym_SPACE,
  [807] = 1,
    ACTIONS(235), 1,
      anon_sym_SPACE,
  [811] = 1,
    ACTIONS(237), 1,
      anon_sym_SPACE,
  [815] = 1,
    ACTIONS(239), 1,
      anon_sym_SQUOTE,
  [819] = 1,
    ACTIONS(117), 1,
      anon_sym_LPAREN,
  [823] = 1,
    ACTIONS(241), 1,
      anon_sym_RBRACK,
  [827] = 1,
    ACTIONS(243), 1,
      anon_sym_LF,
  [831] = 1,
    ACTIONS(245), 1,
      anon_sym_SPACE,
  [835] = 1,
    ACTIONS(247), 1,
      anon_sym_LF,
  [839] = 1,
    ACTIONS(249), 1,
      anon_sym_LF,
  [843] = 1,
    ACTIONS(251), 1,
      anon_sym_SPACE,
  [847] = 1,
    ACTIONS(253), 1,
      sym_identifier,
  [851] = 1,
    ACTIONS(255), 1,
      anon_sym_EQ,
  [855] = 1,
    ACTIONS(257), 1,
      anon_sym_SPACE,
  [859] = 1,
    ACTIONS(259), 1,
      anon_sym_SPACE,
  [863] = 1,
    ACTIONS(261), 1,
      anon_sym_LF,
  [867] = 1,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
  [871] = 1,
    ACTIONS(263), 1,
      anon_sym_SPACE,
  [875] = 1,
    ACTIONS(265), 1,
      anon_sym_SPACE,
  [879] = 1,
    ACTIONS(267), 1,
      anon_sym_SPACE,
  [883] = 1,
    ACTIONS(269), 1,
      anon_sym_DOT,
  [887] = 1,
    ACTIONS(271), 1,
      anon_sym_LF,
  [891] = 1,
    ACTIONS(273), 1,
      anon_sym_SPACE,
  [895] = 1,
    ACTIONS(275), 1,
      anon_sym_SPACE,
  [899] = 1,
    ACTIONS(277), 1,
      anon_sym_SPACE,
  [903] = 1,
    ACTIONS(279), 1,
      anon_sym_LF,
  [907] = 1,
    ACTIONS(281), 1,
      anon_sym_SPACE,
  [911] = 1,
    ACTIONS(283), 1,
      anon_sym_SPACE,
  [915] = 1,
    ACTIONS(285), 1,
      anon_sym_SEMI,
  [919] = 1,
    ACTIONS(287), 1,
      anon_sym_SEMI,
  [923] = 1,
    ACTIONS(289), 1,
      anon_sym_SPACE,
  [927] = 1,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
  [931] = 1,
    ACTIONS(137), 1,
      anon_sym_LPAREN,
  [935] = 1,
    ACTIONS(291), 1,
      anon_sym_RBRACE,
  [939] = 1,
    ACTIONS(187), 1,
      anon_sym_set,
  [943] = 1,
    ACTIONS(293), 1,
      anon_sym_SPACE,
  [947] = 1,
    ACTIONS(295), 1,
      anon_sym_SPACE,
  [951] = 1,
    ACTIONS(297), 1,
      anon_sym_LF,
  [955] = 1,
    ACTIONS(299), 1,
      anon_sym_SPACE,
  [959] = 1,
    ACTIONS(301), 1,
      anon_sym_LBRACE,
  [963] = 1,
    ACTIONS(303), 1,
      anon_sym_LF,
  [967] = 1,
    ACTIONS(305), 1,
      anon_sym_RBRACE,
  [971] = 1,
    ACTIONS(307), 1,
      anon_sym_LF,
  [975] = 1,
    ACTIONS(309), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 29,
  [SMALL_STATE(4)] = 58,
  [SMALL_STATE(5)] = 84,
  [SMALL_STATE(6)] = 114,
  [SMALL_STATE(7)] = 144,
  [SMALL_STATE(8)] = 168,
  [SMALL_STATE(9)] = 192,
  [SMALL_STATE(10)] = 213,
  [SMALL_STATE(11)] = 235,
  [SMALL_STATE(12)] = 257,
  [SMALL_STATE(13)] = 275,
  [SMALL_STATE(14)] = 293,
  [SMALL_STATE(15)] = 310,
  [SMALL_STATE(16)] = 323,
  [SMALL_STATE(17)] = 332,
  [SMALL_STATE(18)] = 349,
  [SMALL_STATE(19)] = 366,
  [SMALL_STATE(20)] = 383,
  [SMALL_STATE(21)] = 400,
  [SMALL_STATE(22)] = 408,
  [SMALL_STATE(23)] = 420,
  [SMALL_STATE(24)] = 432,
  [SMALL_STATE(25)] = 448,
  [SMALL_STATE(26)] = 456,
  [SMALL_STATE(27)] = 464,
  [SMALL_STATE(28)] = 480,
  [SMALL_STATE(29)] = 492,
  [SMALL_STATE(30)] = 508,
  [SMALL_STATE(31)] = 521,
  [SMALL_STATE(32)] = 530,
  [SMALL_STATE(33)] = 543,
  [SMALL_STATE(34)] = 552,
  [SMALL_STATE(35)] = 558,
  [SMALL_STATE(36)] = 568,
  [SMALL_STATE(37)] = 574,
  [SMALL_STATE(38)] = 580,
  [SMALL_STATE(39)] = 588,
  [SMALL_STATE(40)] = 594,
  [SMALL_STATE(41)] = 600,
  [SMALL_STATE(42)] = 606,
  [SMALL_STATE(43)] = 616,
  [SMALL_STATE(44)] = 621,
  [SMALL_STATE(45)] = 628,
  [SMALL_STATE(46)] = 633,
  [SMALL_STATE(47)] = 640,
  [SMALL_STATE(48)] = 647,
  [SMALL_STATE(49)] = 652,
  [SMALL_STATE(50)] = 659,
  [SMALL_STATE(51)] = 664,
  [SMALL_STATE(52)] = 669,
  [SMALL_STATE(53)] = 676,
  [SMALL_STATE(54)] = 683,
  [SMALL_STATE(55)] = 690,
  [SMALL_STATE(56)] = 697,
  [SMALL_STATE(57)] = 702,
  [SMALL_STATE(58)] = 709,
  [SMALL_STATE(59)] = 716,
  [SMALL_STATE(60)] = 723,
  [SMALL_STATE(61)] = 727,
  [SMALL_STATE(62)] = 731,
  [SMALL_STATE(63)] = 735,
  [SMALL_STATE(64)] = 739,
  [SMALL_STATE(65)] = 743,
  [SMALL_STATE(66)] = 747,
  [SMALL_STATE(67)] = 751,
  [SMALL_STATE(68)] = 755,
  [SMALL_STATE(69)] = 759,
  [SMALL_STATE(70)] = 763,
  [SMALL_STATE(71)] = 767,
  [SMALL_STATE(72)] = 771,
  [SMALL_STATE(73)] = 775,
  [SMALL_STATE(74)] = 779,
  [SMALL_STATE(75)] = 783,
  [SMALL_STATE(76)] = 787,
  [SMALL_STATE(77)] = 791,
  [SMALL_STATE(78)] = 795,
  [SMALL_STATE(79)] = 799,
  [SMALL_STATE(80)] = 803,
  [SMALL_STATE(81)] = 807,
  [SMALL_STATE(82)] = 811,
  [SMALL_STATE(83)] = 815,
  [SMALL_STATE(84)] = 819,
  [SMALL_STATE(85)] = 823,
  [SMALL_STATE(86)] = 827,
  [SMALL_STATE(87)] = 831,
  [SMALL_STATE(88)] = 835,
  [SMALL_STATE(89)] = 839,
  [SMALL_STATE(90)] = 843,
  [SMALL_STATE(91)] = 847,
  [SMALL_STATE(92)] = 851,
  [SMALL_STATE(93)] = 855,
  [SMALL_STATE(94)] = 859,
  [SMALL_STATE(95)] = 863,
  [SMALL_STATE(96)] = 867,
  [SMALL_STATE(97)] = 871,
  [SMALL_STATE(98)] = 875,
  [SMALL_STATE(99)] = 879,
  [SMALL_STATE(100)] = 883,
  [SMALL_STATE(101)] = 887,
  [SMALL_STATE(102)] = 891,
  [SMALL_STATE(103)] = 895,
  [SMALL_STATE(104)] = 899,
  [SMALL_STATE(105)] = 903,
  [SMALL_STATE(106)] = 907,
  [SMALL_STATE(107)] = 911,
  [SMALL_STATE(108)] = 915,
  [SMALL_STATE(109)] = 919,
  [SMALL_STATE(110)] = 923,
  [SMALL_STATE(111)] = 927,
  [SMALL_STATE(112)] = 931,
  [SMALL_STATE(113)] = 935,
  [SMALL_STATE(114)] = 939,
  [SMALL_STATE(115)] = 943,
  [SMALL_STATE(116)] = 947,
  [SMALL_STATE(117)] = 951,
  [SMALL_STATE(118)] = 955,
  [SMALL_STATE(119)] = 959,
  [SMALL_STATE(120)] = 963,
  [SMALL_STATE(121)] = 967,
  [SMALL_STATE(122)] = 971,
  [SMALL_STATE(123)] = 975,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__array_modifier, 2, 0, 0),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__array_modifier, 2, 0, 0), SHIFT_REPEAT(54),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_simple_type, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(100),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [84] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [87] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__ref_modifier, 2, 0, 0),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__ref_modifier, 2, 0, 0), SHIFT_REPEAT(23),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__array_modifier, 3, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_type, 4, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal_content, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal_content, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_default_value, 1, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_signature, 7, 0, 4),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg, 3, 0, 6),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_negative_literal, 2, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_char_literal, 3, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_signature, 5, 0, 3),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg, 7, 0, 6),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_list, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 3, 0, 1),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace_part, 3, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 4, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_list, 1, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_list, 4, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [167] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [169] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_list, 4, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_signature, 5, 0, 2),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_getter, 4, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_signature, 8, 0, 5),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [201] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_signature, 9, 0, 2),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_signature, 9, 0, 4),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_signature, 9, 0, 3),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_signature, 7, 0, 3),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_accessibility, 1, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_signature, 1, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_signature, 10, 0, 7),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_getter, 2, 0, 0),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setter, 2, 0, 0),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace_part, 1, 0, 0),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_signature, 11, 0, 4),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_signature, 11, 0, 3),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [295] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setter, 4, 0, 0),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_signature, 13, 0, 4),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [303] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_signature, 13, 0, 3),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_signature, 15, 0, 4),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_noogle(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "noogle",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
