/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 99
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 68
#define ALIAS_COUNT 0
#define TOKEN_COUNT 41
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 9
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 8
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_LF = 2,
  anon_sym_DOT = 3,
  anon_sym_static = 4,
  anon_sym_LBRACE = 5,
  anon_sym_RBRACE = 6,
  anon_sym_get = 7,
  anon_sym_SEMI = 8,
  anon_sym_set = 9,
  anon_sym_none = 10,
  anon_sym_private = 11,
  anon_sym_protectedandinternal = 12,
  anon_sym_protected = 13,
  anon_sym_internal = 14,
  anon_sym_protectedorinternal = 15,
  anon_sym_public = 16,
  anon_sym_DOTctor = 17,
  anon_sym_LPAREN = 18,
  anon_sym_RPAREN = 19,
  anon_sym_COMMA = 20,
  anon_sym_EQ = 21,
  anon_sym_enum = 22,
  anon_sym_LBRACK = 23,
  anon_sym_RBRACK = 24,
  anon_sym_LT = 25,
  anon_sym_GT = 26,
  sym_null_literal = 27,
  anon_sym_SQUOTE = 28,
  sym_character_literal_content = 29,
  anon_sym_DQUOTE = 30,
  aux_sym_string_literal_content_token1 = 31,
  aux_sym_string_literal_content_token2 = 32,
  sym_escape_sequence = 33,
  sym_integer_literal = 34,
  sym_real_literal = 35,
  anon_sym_DASH = 36,
  anon_sym_true = 37,
  anon_sym_false = 38,
  sym__commas = 39,
  sym__refs = 40,
  sym_source_file = 41,
  sym_definition = 42,
  sym_path = 43,
  sym_namespace_part = 44,
  sym_signature = 45,
  sym_property_signature = 46,
  sym_getter = 47,
  sym_setter = 48,
  sym_accessibility = 49,
  sym_method_signature = 50,
  sym_arg_list = 51,
  sym_arg = 52,
  sym_enum_signature = 53,
  sym_type_list = 54,
  sym_type = 55,
  aux_sym__array_modifier = 56,
  aux_sym__ref_modifier = 57,
  sym_generic_type = 58,
  sym_simple_type = 59,
  sym_default_value = 60,
  sym_char_literal = 61,
  sym_string_literal = 62,
  sym_string_literal_content = 63,
  sym_negative_literal = 64,
  sym_boolean_literal = 65,
  aux_sym_source_file_repeat1 = 66,
  aux_sym_string_literal_repeat1 = 67,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_LF] = "\n",
  [anon_sym_DOT] = ".",
  [anon_sym_static] = "static",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_get] = "get",
  [anon_sym_SEMI] = ";",
  [anon_sym_set] = "set",
  [anon_sym_none] = "none",
  [anon_sym_private] = "private",
  [anon_sym_protectedandinternal] = "protectedandinternal",
  [anon_sym_protected] = "protected",
  [anon_sym_internal] = "internal",
  [anon_sym_protectedorinternal] = "protectedorinternal",
  [anon_sym_public] = "public",
  [anon_sym_DOTctor] = ".ctor",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [anon_sym_EQ] = "=",
  [anon_sym_enum] = "enum",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [sym_null_literal] = "null_literal",
  [anon_sym_SQUOTE] = "'",
  [sym_character_literal_content] = "character_literal_content",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_literal_content_token1] = "string_literal_content_token1",
  [aux_sym_string_literal_content_token2] = "string_literal_content_token2",
  [sym_escape_sequence] = "escape_sequence",
  [sym_integer_literal] = "integer_literal",
  [sym_real_literal] = "real_literal",
  [anon_sym_DASH] = "-",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym__commas] = "_commas",
  [sym__refs] = "_refs",
  [sym_source_file] = "source_file",
  [sym_definition] = "definition",
  [sym_path] = "path",
  [sym_namespace_part] = "namespace_part",
  [sym_signature] = "signature",
  [sym_property_signature] = "property_signature",
  [sym_getter] = "getter",
  [sym_setter] = "setter",
  [sym_accessibility] = "accessibility",
  [sym_method_signature] = "method_signature",
  [sym_arg_list] = "arg_list",
  [sym_arg] = "arg",
  [sym_enum_signature] = "enum_signature",
  [sym_type_list] = "type_list",
  [sym_type] = "type",
  [aux_sym__array_modifier] = "_array_modifier",
  [aux_sym__ref_modifier] = "_ref_modifier",
  [sym_generic_type] = "generic_type",
  [sym_simple_type] = "simple_type",
  [sym_default_value] = "default_value",
  [sym_char_literal] = "char_literal",
  [sym_string_literal] = "string_literal",
  [sym_string_literal_content] = "string_literal_content",
  [sym_negative_literal] = "negative_literal",
  [sym_boolean_literal] = "boolean_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_string_literal_repeat1] = "string_literal_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_static] = anon_sym_static,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_get] = anon_sym_get,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [anon_sym_set] = anon_sym_set,
  [anon_sym_none] = anon_sym_none,
  [anon_sym_private] = anon_sym_private,
  [anon_sym_protectedandinternal] = anon_sym_protectedandinternal,
  [anon_sym_protected] = anon_sym_protected,
  [anon_sym_internal] = anon_sym_internal,
  [anon_sym_protectedorinternal] = anon_sym_protectedorinternal,
  [anon_sym_public] = anon_sym_public,
  [anon_sym_DOTctor] = anon_sym_DOTctor,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_enum] = anon_sym_enum,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [sym_null_literal] = sym_null_literal,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [sym_character_literal_content] = sym_character_literal_content,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_literal_content_token1] = aux_sym_string_literal_content_token1,
  [aux_sym_string_literal_content_token2] = aux_sym_string_literal_content_token2,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_integer_literal] = sym_integer_literal,
  [sym_real_literal] = sym_real_literal,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym__commas] = sym__commas,
  [sym__refs] = sym__refs,
  [sym_source_file] = sym_source_file,
  [sym_definition] = sym_definition,
  [sym_path] = sym_path,
  [sym_namespace_part] = sym_namespace_part,
  [sym_signature] = sym_signature,
  [sym_property_signature] = sym_property_signature,
  [sym_getter] = sym_getter,
  [sym_setter] = sym_setter,
  [sym_accessibility] = sym_accessibility,
  [sym_method_signature] = sym_method_signature,
  [sym_arg_list] = sym_arg_list,
  [sym_arg] = sym_arg,
  [sym_enum_signature] = sym_enum_signature,
  [sym_type_list] = sym_type_list,
  [sym_type] = sym_type,
  [aux_sym__array_modifier] = aux_sym__array_modifier,
  [aux_sym__ref_modifier] = aux_sym__ref_modifier,
  [sym_generic_type] = sym_generic_type,
  [sym_simple_type] = sym_simple_type,
  [sym_default_value] = sym_default_value,
  [sym_char_literal] = sym_char_literal,
  [sym_string_literal] = sym_string_literal,
  [sym_string_literal_content] = sym_string_literal_content,
  [sym_negative_literal] = sym_negative_literal,
  [sym_boolean_literal] = sym_boolean_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_string_literal_repeat1] = aux_sym_string_literal_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_static] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_get] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_set] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_none] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_private] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_protectedandinternal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_protected] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_internal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_protectedorinternal] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_public] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOTctor] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_enum] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_null_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_character_literal_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_content_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_content_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_real_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym__commas] = {
    .visible = false,
    .named = true,
  },
  [sym__refs] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_path] = {
    .visible = true,
    .named = true,
  },
  [sym_namespace_part] = {
    .visible = true,
    .named = true,
  },
  [sym_signature] = {
    .visible = true,
    .named = true,
  },
  [sym_property_signature] = {
    .visible = true,
    .named = true,
  },
  [sym_getter] = {
    .visible = true,
    .named = true,
  },
  [sym_setter] = {
    .visible = true,
    .named = true,
  },
  [sym_accessibility] = {
    .visible = true,
    .named = true,
  },
  [sym_method_signature] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_list] = {
    .visible = true,
    .named = true,
  },
  [sym_arg] = {
    .visible = true,
    .named = true,
  },
  [sym_enum_signature] = {
    .visible = true,
    .named = true,
  },
  [sym_type_list] = {
    .visible = true,
    .named = true,
  },
  [sym_type] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__array_modifier] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__ref_modifier] = {
    .visible = false,
    .named = false,
  },
  [sym_generic_type] = {
    .visible = true,
    .named = true,
  },
  [sym_simple_type] = {
    .visible = true,
    .named = true,
  },
  [sym_default_value] = {
    .visible = true,
    .named = true,
  },
  [sym_char_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal_content] = {
    .visible = true,
    .named = true,
  },
  [sym_negative_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arg_name = 1,
  field_arg_type = 2,
  field_class = 3,
  field_enum = 4,
  field_field = 5,
  field_name = 6,
  field_namespace = 7,
  field_parameters = 8,
  field_return_type = 9,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arg_name] = "arg_name",
  [field_arg_type] = "arg_type",
  [field_class] = "class",
  [field_enum] = "enum",
  [field_field] = "field",
  [field_name] = "name",
  [field_namespace] = "namespace",
  [field_parameters] = "parameters",
  [field_return_type] = "return_type",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 2},
  [4] = {.index = 6, .length = 2},
  [5] = {.index = 8, .length = 3},
  [6] = {.index = 11, .length = 2},
  [7] = {.index = 13, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_class, 2},
    {field_namespace, 0},
  [2] =
    {field_name, 2},
    {field_return_type, 1},
  [4] =
    {field_enum, 1},
    {field_field, 3},
  [6] =
    {field_name, 3},
    {field_return_type, 2},
  [8] =
    {field_name, 2},
    {field_parameters, 4},
    {field_return_type, 1},
  [11] =
    {field_arg_name, 1},
    {field_arg_type, 0},
  [13] =
    {field_name, 3},
    {field_parameters, 5},
    {field_return_type, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(40);
      ADVANCE_MAP(
        '\n', 41,
        '"', 60,
        '\'', 58,
        '(', 47,
        ')', 48,
        ',', 50,
        '-', 88,
        '.', 42,
        '0', 73,
        ';', 45,
        '<', 54,
        '=', 51,
        '>', 55,
        '[', 52,
        '\\', 4,
        ']', 53,
        'f', 96,
        'n', 105,
        't', 102,
        '{', 43,
        '}', 44,
      );
      if (lookahead == '\r' ||
          lookahead == ' ') SKIP(38);
      if (('&' <= lookahead && lookahead <= '*')) ADVANCE(108);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(74);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '"', 60,
        '\'', 58,
        ',', 107,
        '-', 87,
        '.', 26,
        '0', 71,
        ']', 53,
        'f', 11,
        'n', 24,
        't', 20,
      );
      if (lookahead == '\r' ||
          lookahead == ' ') SKIP(1);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == '\r' ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(62);
      END_STATE();
    case 3:
      if (lookahead == '.') ADVANCE(42);
      if (lookahead == '\r' ||
          lookahead == ' ') SKIP(3);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        'U', 64,
        'u', 66,
        'x', 65,
        '"', 67,
        '\'', 67,
        '0', 67,
        '?', 67,
        '\\', 67,
        'a', 67,
        'b', 67,
        'e', 67,
        'f', 67,
        'n', 67,
        'r', 67,
        't', 67,
        'v', 67,
      );
      if (lookahead != 0) ADVANCE(63);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        'U', 29,
        'u', 34,
        'x', 31,
        '"', 67,
        '\'', 67,
        '0', 67,
        '?', 67,
        '\\', 67,
        'a', 67,
        'b', 67,
        'e', 67,
        'f', 67,
        'n', 67,
        'r', 67,
        't', 67,
        'v', 67,
      );
      END_STATE();
    case 6:
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead == '\r' ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(59);
      END_STATE();
    case 7:
      if (lookahead == '_') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 8:
      if (lookahead == '_') ADVANCE(8);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(77);
      END_STATE();
    case 9:
      if (lookahead == '_') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(78);
      END_STATE();
    case 10:
      if (lookahead == '_') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(85);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'c') ADVANCE(22);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(89);
      END_STATE();
    case 14:
      if (lookahead == 'e') ADVANCE(91);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(21);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(56);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(16);
      END_STATE();
    case 18:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(46);
      END_STATE();
    case 20:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 21:
      if (lookahead == 's') ADVANCE(14);
      END_STATE();
    case 22:
      if (lookahead == 't') ADVANCE(18);
      END_STATE();
    case 23:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 24:
      if (lookahead == 'u') ADVANCE(17);
      END_STATE();
    case 25:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(86);
      END_STATE();
    case 26:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(85);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(86);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(67);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(37);
      END_STATE();
    case 30:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(69);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(30);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(28);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(32);
      END_STATE();
    case 34:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(33);
      END_STATE();
    case 35:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(34);
      END_STATE();
    case 36:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(35);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(36);
      END_STATE();
    case 38:
      if (eof) ADVANCE(40);
      ADVANCE_MAP(
        '\n', 41,
        '"', 60,
        '\'', 58,
        '(', 47,
        ')', 48,
        ',', 50,
        '-', 88,
        '.', 42,
        '0', 73,
        ';', 45,
        '<', 54,
        '=', 51,
        '>', 55,
        '[', 52,
        '\\', 5,
        ']', 53,
        'f', 96,
        'n', 105,
        't', 102,
        '{', 43,
        '}', 44,
      );
      if (lookahead == '\r' ||
          lookahead == ' ') SKIP(38);
      if (('&' <= lookahead && lookahead <= '*')) ADVANCE(108);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(74);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 39:
      if (eof) ADVANCE(40);
      ADVANCE_MAP(
        '\n', 41,
        ')', 48,
        ',', 49,
        '.', 12,
        '<', 54,
        '=', 51,
        '>', 55,
        '[', 52,
        '}', 44,
      );
      if (lookahead == '\r' ||
          lookahead == ' ') SKIP(39);
      if (lookahead == '&' ||
          lookahead == '*') ADVANCE(108);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_DOTctor);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_COMMA);
      if (lookahead == ',') ADVANCE(107);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_null_literal);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_null_literal);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_character_literal_content);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_string_literal_content_token1);
      if (lookahead == '\r' ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(62);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_string_literal_content_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_string_literal_content_token2);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_string_literal_content_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(37);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_string_literal_content_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(30);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_string_literal_content_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(33);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(67);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(68);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_integer_literal);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_integer_literal);
      ADVANCE_MAP(
        '.', 26,
        '_', 7,
        'B', 8,
        'b', 8,
        'E', 25,
        'e', 25,
        'L', 82,
        'l', 82,
        'U', 80,
        'u', 80,
        'X', 9,
        'x', 9,
        'D', 84,
        'F', 84,
        'M', 84,
        'd', 84,
        'f', 84,
        'm', 84,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_integer_literal);
      ADVANCE_MAP(
        '.', 26,
        '_', 7,
        'E', 25,
        'e', 25,
        'L', 82,
        'l', 82,
        'U', 80,
        'u', 80,
        'D', 84,
        'F', 84,
        'M', 84,
        'd', 84,
        'f', 84,
        'm', 84,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_integer_literal);
      ADVANCE_MAP(
        '_', 93,
        'B', 94,
        'b', 94,
        'L', 81,
        'l', 81,
        'U', 79,
        'u', 79,
        'X', 95,
        'x', 95,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '_') ADVANCE(93);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(81);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '_') ADVANCE(94);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(81);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(79);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(75);
      if (lookahead == '-' ||
          ('2' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '_') ADVANCE(95);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(81);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(76);
      if (lookahead == '-' ||
          ('G' <= lookahead && lookahead <= 'Z') ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '_') ADVANCE(8);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(82);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(80);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '_') ADVANCE(9);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(82);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(83);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == 'L' ||
          lookahead == 'l') ADVANCE(70);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(83);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(70);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_real_literal);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_real_literal);
      ADVANCE_MAP(
        '_', 10,
        'E', 25,
        'e', 25,
        'D', 84,
        'F', 84,
        'M', 84,
        'd', 84,
        'f', 84,
        'm', 84,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(85);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_real_literal);
      if (lookahead == 'D' ||
          lookahead == 'F' ||
          lookahead == 'M' ||
          lookahead == 'd' ||
          lookahead == 'f' ||
          lookahead == 'm') ADVANCE(84);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(86);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(93);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(94);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(75);
      if (lookahead == '-' ||
          ('2' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '_') ADVANCE(95);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(76);
      if (lookahead == '-' ||
          ('G' <= lookahead && lookahead <= 'Z') ||
          ('g' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(99);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(90);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(92);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(103);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(57);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(100);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(104);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(98);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(97);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(101);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(106);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym__commas);
      if (lookahead == ',') ADVANCE(107);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym__refs);
      if (lookahead == '&' ||
          lookahead == '*') ADVANCE(108);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'e') ADVANCE(1);
      if (lookahead == 'g') ADVANCE(2);
      if (lookahead == 'i') ADVANCE(3);
      if (lookahead == 'n') ADVANCE(4);
      if (lookahead == 'p') ADVANCE(5);
      if (lookahead == 's') ADVANCE(6);
      if (lookahead == '\r' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 2:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 3:
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 4:
      if (lookahead == 'o') ADVANCE(10);
      END_STATE();
    case 5:
      if (lookahead == 'r') ADVANCE(11);
      if (lookahead == 'u') ADVANCE(12);
      END_STATE();
    case 6:
      if (lookahead == 'e') ADVANCE(13);
      if (lookahead == 't') ADVANCE(14);
      END_STATE();
    case 7:
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 8:
      if (lookahead == 't') ADVANCE(16);
      END_STATE();
    case 9:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 10:
      if (lookahead == 'n') ADVANCE(18);
      END_STATE();
    case 11:
      if (lookahead == 'i') ADVANCE(19);
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 12:
      if (lookahead == 'b') ADVANCE(21);
      END_STATE();
    case 13:
      if (lookahead == 't') ADVANCE(22);
      END_STATE();
    case 14:
      if (lookahead == 'a') ADVANCE(23);
      END_STATE();
    case 15:
      if (lookahead == 'm') ADVANCE(24);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_get);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(25);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(26);
      END_STATE();
    case 19:
      if (lookahead == 'v') ADVANCE(27);
      END_STATE();
    case 20:
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 21:
      if (lookahead == 'l') ADVANCE(29);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_set);
      END_STATE();
    case 23:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_enum);
      END_STATE();
    case 25:
      if (lookahead == 'r') ADVANCE(31);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_none);
      END_STATE();
    case 27:
      if (lookahead == 'a') ADVANCE(32);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 29:
      if (lookahead == 'i') ADVANCE(34);
      END_STATE();
    case 30:
      if (lookahead == 'i') ADVANCE(35);
      END_STATE();
    case 31:
      if (lookahead == 'n') ADVANCE(36);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(37);
      END_STATE();
    case 33:
      if (lookahead == 'c') ADVANCE(38);
      END_STATE();
    case 34:
      if (lookahead == 'c') ADVANCE(39);
      END_STATE();
    case 35:
      if (lookahead == 'c') ADVANCE(40);
      END_STATE();
    case 36:
      if (lookahead == 'a') ADVANCE(41);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 38:
      if (lookahead == 't') ADVANCE(43);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_public);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_static);
      END_STATE();
    case 41:
      if (lookahead == 'l') ADVANCE(44);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_private);
      END_STATE();
    case 43:
      if (lookahead == 'e') ADVANCE(45);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_internal);
      END_STATE();
    case 45:
      if (lookahead == 'd') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_protected);
      if (lookahead == 'a') ADVANCE(47);
      if (lookahead == 'o') ADVANCE(48);
      END_STATE();
    case 47:
      if (lookahead == 'n') ADVANCE(49);
      END_STATE();
    case 48:
      if (lookahead == 'r') ADVANCE(50);
      END_STATE();
    case 49:
      if (lookahead == 'd') ADVANCE(51);
      END_STATE();
    case 50:
      if (lookahead == 'i') ADVANCE(52);
      END_STATE();
    case 51:
      if (lookahead == 'i') ADVANCE(53);
      END_STATE();
    case 52:
      if (lookahead == 'n') ADVANCE(54);
      END_STATE();
    case 53:
      if (lookahead == 'n') ADVANCE(55);
      END_STATE();
    case 54:
      if (lookahead == 't') ADVANCE(56);
      END_STATE();
    case 55:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 56:
      if (lookahead == 'e') ADVANCE(58);
      END_STATE();
    case 57:
      if (lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 58:
      if (lookahead == 'r') ADVANCE(60);
      END_STATE();
    case 59:
      if (lookahead == 'r') ADVANCE(61);
      END_STATE();
    case 60:
      if (lookahead == 'n') ADVANCE(62);
      END_STATE();
    case 61:
      if (lookahead == 'n') ADVANCE(63);
      END_STATE();
    case 62:
      if (lookahead == 'a') ADVANCE(64);
      END_STATE();
    case 63:
      if (lookahead == 'a') ADVANCE(65);
      END_STATE();
    case 64:
      if (lookahead == 'l') ADVANCE(66);
      END_STATE();
    case 65:
      if (lookahead == 'l') ADVANCE(67);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_protectedorinternal);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_protectedandinternal);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 39},
  [2] = {.lex_state = 39},
  [3] = {.lex_state = 39},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 39},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 39},
  [8] = {.lex_state = 39},
  [9] = {.lex_state = 39},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 39},
  [12] = {.lex_state = 39},
  [13] = {.lex_state = 39},
  [14] = {.lex_state = 39},
  [15] = {.lex_state = 39},
  [16] = {.lex_state = 39},
  [17] = {.lex_state = 39},
  [18] = {.lex_state = 39},
  [19] = {.lex_state = 39},
  [20] = {.lex_state = 39},
  [21] = {.lex_state = 39},
  [22] = {.lex_state = 39},
  [23] = {.lex_state = 39},
  [24] = {.lex_state = 39},
  [25] = {.lex_state = 39},
  [26] = {.lex_state = 39},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 39},
  [31] = {.lex_state = 39},
  [32] = {.lex_state = 39},
  [33] = {.lex_state = 39},
  [34] = {.lex_state = 39},
  [35] = {.lex_state = 39},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 39},
  [41] = {.lex_state = 39},
  [42] = {.lex_state = 39},
  [43] = {.lex_state = 39},
  [44] = {.lex_state = 39},
  [45] = {.lex_state = 39},
  [46] = {.lex_state = 39},
  [47] = {.lex_state = 39},
  [48] = {.lex_state = 39},
  [49] = {.lex_state = 39},
  [50] = {.lex_state = 39},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 6},
  [53] = {.lex_state = 39},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 39},
  [56] = {.lex_state = 39},
  [57] = {.lex_state = 39},
  [58] = {.lex_state = 39},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 39},
  [61] = {.lex_state = 39},
  [62] = {.lex_state = 39},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 39},
  [71] = {.lex_state = 39},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 39},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 39},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 39},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_static] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_get] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [anon_sym_set] = ACTIONS(1),
    [anon_sym_none] = ACTIONS(1),
    [anon_sym_private] = ACTIONS(1),
    [anon_sym_protectedandinternal] = ACTIONS(1),
    [anon_sym_protected] = ACTIONS(1),
    [anon_sym_internal] = ACTIONS(1),
    [anon_sym_protectedorinternal] = ACTIONS(1),
    [anon_sym_public] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_enum] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [sym_null_literal] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [aux_sym_string_literal_content_token2] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym__commas] = ACTIONS(1),
    [sym__refs] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(63),
    [sym_definition] = STATE(20),
    [sym_path] = STATE(2),
    [sym_namespace_part] = STATE(89),
    [aux_sym_source_file_repeat1] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(9), 1,
      anon_sym_protected,
    ACTIONS(11), 1,
      anon_sym_enum,
    STATE(31), 1,
      sym_accessibility,
    STATE(80), 1,
      sym_signature,
    STATE(66), 3,
      sym_property_signature,
      sym_method_signature,
      sym_enum_signature,
    ACTIONS(7), 6,
      anon_sym_none,
      anon_sym_private,
      anon_sym_protectedandinternal,
      anon_sym_internal,
      anon_sym_protectedorinternal,
      anon_sym_public,
  [26] = 8,
    ACTIONS(9), 1,
      anon_sym_protected,
    ACTIONS(13), 1,
      anon_sym_RBRACE,
    ACTIONS(15), 1,
      anon_sym_get,
    ACTIONS(17), 1,
      anon_sym_set,
    STATE(7), 1,
      sym_getter,
    STATE(49), 1,
      sym_accessibility,
    STATE(81), 1,
      sym_setter,
    ACTIONS(7), 6,
      anon_sym_none,
      anon_sym_private,
      anon_sym_protectedandinternal,
      anon_sym_internal,
      anon_sym_protectedorinternal,
      anon_sym_public,
  [56] = 8,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      sym_integer_literal,
    ACTIONS(27), 1,
      anon_sym_DASH,
    STATE(95), 1,
      sym_default_value,
    ACTIONS(19), 2,
      sym_null_literal,
      sym_real_literal,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(40), 4,
      sym_char_literal,
      sym_string_literal,
      sym_negative_literal,
      sym_boolean_literal,
  [86] = 8,
    ACTIONS(9), 1,
      anon_sym_protected,
    ACTIONS(15), 1,
      anon_sym_get,
    ACTIONS(17), 1,
      anon_sym_set,
    ACTIONS(31), 1,
      anon_sym_RBRACE,
    STATE(8), 1,
      sym_getter,
    STATE(49), 1,
      sym_accessibility,
    STATE(67), 1,
      sym_setter,
    ACTIONS(7), 6,
      anon_sym_none,
      anon_sym_private,
      anon_sym_protectedandinternal,
      anon_sym_internal,
      anon_sym_protectedorinternal,
      anon_sym_public,
  [116] = 8,
    ACTIONS(21), 1,
      anon_sym_SQUOTE,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      sym_integer_literal,
    ACTIONS(27), 1,
      anon_sym_DASH,
    STATE(48), 1,
      sym_default_value,
    ACTIONS(19), 2,
      sym_null_literal,
      sym_real_literal,
    ACTIONS(29), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(40), 4,
      sym_char_literal,
      sym_string_literal,
      sym_negative_literal,
      sym_boolean_literal,
  [146] = 6,
    ACTIONS(9), 1,
      anon_sym_protected,
    ACTIONS(17), 1,
      anon_sym_set,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
    STATE(74), 1,
      sym_setter,
    STATE(75), 1,
      sym_accessibility,
    ACTIONS(7), 6,
      anon_sym_none,
      anon_sym_private,
      anon_sym_protectedandinternal,
      anon_sym_internal,
      anon_sym_protectedorinternal,
      anon_sym_public,
  [170] = 6,
    ACTIONS(9), 1,
      anon_sym_protected,
    ACTIONS(17), 1,
      anon_sym_set,
    ACTIONS(35), 1,
      anon_sym_RBRACE,
    STATE(75), 1,
      sym_accessibility,
    STATE(87), 1,
      sym_setter,
    ACTIONS(7), 6,
      anon_sym_none,
      anon_sym_private,
      anon_sym_protectedandinternal,
      anon_sym_internal,
      anon_sym_protectedorinternal,
      anon_sym_public,
  [194] = 6,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(41), 1,
      anon_sym_LT,
    ACTIONS(43), 1,
      sym__refs,
    STATE(13), 1,
      aux_sym__array_modifier,
    STATE(22), 1,
      aux_sym__ref_modifier,
    ACTIONS(37), 4,
      anon_sym_DOTctor,
      anon_sym_COMMA,
      anon_sym_GT,
      sym_identifier,
  [216] = 3,
    ACTIONS(45), 1,
      anon_sym_DOT,
    ACTIONS(49), 1,
      anon_sym_protected,
    ACTIONS(47), 7,
      anon_sym_none,
      anon_sym_private,
      anon_sym_protectedandinternal,
      anon_sym_internal,
      anon_sym_protectedorinternal,
      anon_sym_public,
      anon_sym_enum,
  [232] = 2,
    ACTIONS(53), 1,
      anon_sym_protected,
    ACTIONS(51), 8,
      anon_sym_RBRACE,
      anon_sym_set,
      anon_sym_none,
      anon_sym_private,
      anon_sym_protectedandinternal,
      anon_sym_internal,
      anon_sym_protectedorinternal,
      anon_sym_public,
  [246] = 2,
    ACTIONS(57), 1,
      anon_sym_protected,
    ACTIONS(55), 8,
      anon_sym_RBRACE,
      anon_sym_set,
      anon_sym_none,
      anon_sym_private,
      anon_sym_protectedandinternal,
      anon_sym_internal,
      anon_sym_protectedorinternal,
      anon_sym_public,
  [260] = 5,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(61), 1,
      sym__refs,
    STATE(18), 1,
      aux_sym__array_modifier,
    STATE(24), 1,
      aux_sym__ref_modifier,
    ACTIONS(59), 4,
      anon_sym_DOTctor,
      anon_sym_COMMA,
      anon_sym_GT,
      sym_identifier,
  [279] = 5,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(43), 1,
      sym__refs,
    STATE(13), 1,
      aux_sym__array_modifier,
    STATE(22), 1,
      aux_sym__ref_modifier,
    ACTIONS(37), 4,
      anon_sym_DOTctor,
      anon_sym_COMMA,
      anon_sym_GT,
      sym_identifier,
  [298] = 1,
    ACTIONS(63), 7,
      anon_sym_DOTctor,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_LT,
      anon_sym_GT,
      sym_identifier,
      sym__refs,
  [308] = 7,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(67), 1,
      anon_sym_RPAREN,
    STATE(9), 1,
      sym_simple_type,
    STATE(14), 1,
      sym_generic_type,
    STATE(61), 1,
      sym_arg_list,
    STATE(62), 1,
      sym_arg,
    STATE(71), 1,
      sym_type,
  [330] = 7,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(69), 1,
      anon_sym_RPAREN,
    STATE(9), 1,
      sym_simple_type,
    STATE(14), 1,
      sym_generic_type,
    STATE(55), 1,
      sym_arg_list,
    STATE(62), 1,
      sym_arg,
    STATE(71), 1,
      sym_type,
  [352] = 3,
    ACTIONS(73), 1,
      anon_sym_LBRACK,
    STATE(18), 1,
      aux_sym__array_modifier,
    ACTIONS(71), 5,
      anon_sym_DOTctor,
      anon_sym_COMMA,
      anon_sym_GT,
      sym_identifier,
      sym__refs,
  [366] = 1,
    ACTIONS(76), 6,
      anon_sym_DOTctor,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_GT,
      sym_identifier,
      sym__refs,
  [375] = 5,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(78), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_path,
    STATE(89), 1,
      sym_namespace_part,
    STATE(21), 2,
      sym_definition,
      aux_sym_source_file_repeat1,
  [392] = 5,
    ACTIONS(80), 1,
      ts_builtin_sym_end,
    ACTIONS(82), 1,
      sym_identifier,
    STATE(2), 1,
      sym_path,
    STATE(89), 1,
      sym_namespace_part,
    STATE(21), 2,
      sym_definition,
      aux_sym_source_file_repeat1,
  [409] = 3,
    ACTIONS(85), 1,
      sym__refs,
    STATE(26), 1,
      aux_sym__ref_modifier,
    ACTIONS(59), 4,
      anon_sym_DOTctor,
      anon_sym_COMMA,
      anon_sym_GT,
      sym_identifier,
  [422] = 1,
    ACTIONS(71), 6,
      anon_sym_DOTctor,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_GT,
      sym_identifier,
      sym__refs,
  [431] = 3,
    ACTIONS(85), 1,
      sym__refs,
    STATE(26), 1,
      aux_sym__ref_modifier,
    ACTIONS(87), 4,
      anon_sym_DOTctor,
      anon_sym_COMMA,
      anon_sym_GT,
      sym_identifier,
  [444] = 1,
    ACTIONS(89), 6,
      anon_sym_DOTctor,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_GT,
      sym_identifier,
      sym__refs,
  [453] = 3,
    ACTIONS(93), 1,
      sym__refs,
    STATE(26), 1,
      aux_sym__ref_modifier,
    ACTIONS(91), 4,
      anon_sym_DOTctor,
      anon_sym_COMMA,
      anon_sym_GT,
      sym_identifier,
  [466] = 5,
    ACTIONS(96), 1,
      anon_sym_DQUOTE,
    ACTIONS(98), 1,
      aux_sym_string_literal_content_token1,
    ACTIONS(100), 1,
      aux_sym_string_literal_content_token2,
    ACTIONS(102), 1,
      sym_escape_sequence,
    STATE(28), 2,
      sym_string_literal_content,
      aux_sym_string_literal_repeat1,
  [483] = 5,
    ACTIONS(98), 1,
      aux_sym_string_literal_content_token1,
    ACTIONS(100), 1,
      aux_sym_string_literal_content_token2,
    ACTIONS(104), 1,
      anon_sym_DQUOTE,
    ACTIONS(106), 1,
      sym_escape_sequence,
    STATE(29), 2,
      sym_string_literal_content,
      aux_sym_string_literal_repeat1,
  [500] = 5,
    ACTIONS(108), 1,
      anon_sym_DQUOTE,
    ACTIONS(110), 1,
      aux_sym_string_literal_content_token1,
    ACTIONS(113), 1,
      aux_sym_string_literal_content_token2,
    ACTIONS(116), 1,
      sym_escape_sequence,
    STATE(29), 2,
      sym_string_literal_content,
      aux_sym_string_literal_repeat1,
  [517] = 5,
    ACTIONS(65), 1,
      sym_identifier,
    STATE(9), 1,
      sym_simple_type,
    STATE(14), 1,
      sym_generic_type,
    STATE(57), 1,
      sym_type_list,
    STATE(58), 1,
      sym_type,
  [533] = 5,
    ACTIONS(119), 1,
      sym_identifier,
    ACTIONS(121), 1,
      anon_sym_static,
    STATE(9), 1,
      sym_simple_type,
    STATE(14), 1,
      sym_generic_type,
    STATE(47), 1,
      sym_type,
  [549] = 5,
    ACTIONS(65), 1,
      sym_identifier,
    STATE(9), 1,
      sym_simple_type,
    STATE(14), 1,
      sym_generic_type,
    STATE(60), 1,
      sym_arg,
    STATE(71), 1,
      sym_type,
  [565] = 4,
    ACTIONS(65), 1,
      sym_identifier,
    STATE(9), 1,
      sym_simple_type,
    STATE(14), 1,
      sym_generic_type,
    STATE(56), 1,
      sym_type,
  [578] = 1,
    ACTIONS(123), 4,
      anon_sym_static,
      anon_sym_get,
      anon_sym_set,
      sym_identifier,
  [585] = 4,
    ACTIONS(65), 1,
      sym_identifier,
    STATE(9), 1,
      sym_simple_type,
    STATE(14), 1,
      sym_generic_type,
    STATE(53), 1,
      sym_type,
  [598] = 2,
    ACTIONS(127), 1,
      aux_sym_string_literal_content_token1,
    ACTIONS(125), 3,
      anon_sym_DQUOTE,
      aux_sym_string_literal_content_token2,
      sym_escape_sequence,
  [607] = 2,
    ACTIONS(127), 1,
      aux_sym_string_literal_content_token1,
    ACTIONS(125), 3,
      anon_sym_DQUOTE,
      aux_sym_string_literal_content_token2,
      sym_escape_sequence,
  [616] = 3,
    ACTIONS(129), 1,
      anon_sym_LF,
    ACTIONS(131), 1,
      anon_sym_LBRACE,
    ACTIONS(133), 1,
      anon_sym_LPAREN,
  [626] = 3,
    ACTIONS(135), 1,
      anon_sym_LF,
    ACTIONS(137), 1,
      anon_sym_LBRACE,
    ACTIONS(139), 1,
      anon_sym_LPAREN,
  [636] = 1,
    ACTIONS(141), 3,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [642] = 2,
    ACTIONS(145), 1,
      anon_sym_EQ,
    ACTIONS(143), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [650] = 1,
    ACTIONS(147), 3,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [656] = 1,
    ACTIONS(149), 3,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [662] = 1,
    ACTIONS(151), 3,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [668] = 1,
    ACTIONS(153), 3,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [674] = 1,
    ACTIONS(155), 3,
      anon_sym_LF,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [680] = 2,
    ACTIONS(157), 1,
      sym_identifier,
    ACTIONS(159), 1,
      anon_sym_DOTctor,
  [687] = 1,
    ACTIONS(161), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [692] = 2,
    ACTIONS(163), 1,
      anon_sym_get,
    ACTIONS(165), 1,
      anon_sym_set,
  [699] = 1,
    ACTIONS(167), 2,
      ts_builtin_sym_end,
      sym_identifier,
  [704] = 2,
    ACTIONS(169), 1,
      anon_sym_RBRACK,
    ACTIONS(171), 1,
      sym__commas,
  [711] = 2,
    ACTIONS(173), 1,
      sym_character_literal_content,
    ACTIONS(175), 1,
      sym_escape_sequence,
  [718] = 2,
    ACTIONS(177), 1,
      sym_identifier,
    ACTIONS(179), 1,
      anon_sym_DOTctor,
  [725] = 2,
    ACTIONS(181), 1,
      sym_integer_literal,
    ACTIONS(183), 1,
      sym_real_literal,
  [732] = 2,
    ACTIONS(185), 1,
      anon_sym_RPAREN,
    ACTIONS(187), 1,
      anon_sym_COMMA,
  [739] = 1,
    ACTIONS(189), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [744] = 2,
    ACTIONS(191), 1,
      anon_sym_COMMA,
    ACTIONS(193), 1,
      anon_sym_GT,
  [751] = 1,
    ACTIONS(195), 2,
      anon_sym_COMMA,
      anon_sym_GT,
  [756] = 2,
    ACTIONS(197), 1,
      anon_sym_LF,
    ACTIONS(199), 1,
      anon_sym_EQ,
  [763] = 1,
    ACTIONS(201), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [768] = 2,
    ACTIONS(187), 1,
      anon_sym_COMMA,
    ACTIONS(203), 1,
      anon_sym_RPAREN,
  [775] = 1,
    ACTIONS(205), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [780] = 1,
    ACTIONS(207), 1,
      ts_builtin_sym_end,
  [784] = 1,
    ACTIONS(209), 1,
      anon_sym_DOT,
  [788] = 1,
    ACTIONS(211), 1,
      anon_sym_LF,
  [792] = 1,
    ACTIONS(213), 1,
      anon_sym_LF,
  [796] = 1,
    ACTIONS(35), 1,
      anon_sym_RBRACE,
  [800] = 1,
    ACTIONS(215), 1,
      anon_sym_LF,
  [804] = 1,
    ACTIONS(133), 1,
      anon_sym_LPAREN,
  [808] = 1,
    ACTIONS(217), 1,
      sym_identifier,
  [812] = 1,
    ACTIONS(219), 1,
      sym_identifier,
  [816] = 1,
    ACTIONS(221), 1,
      anon_sym_RBRACE,
  [820] = 1,
    ACTIONS(223), 1,
      anon_sym_LF,
  [824] = 1,
    ACTIONS(225), 1,
      anon_sym_RBRACE,
  [828] = 1,
    ACTIONS(165), 1,
      anon_sym_set,
  [832] = 1,
    ACTIONS(227), 1,
      anon_sym_SEMI,
  [836] = 1,
    ACTIONS(229), 1,
      anon_sym_SEMI,
  [840] = 1,
    ACTIONS(231), 1,
      sym_identifier,
  [844] = 1,
    ACTIONS(233), 1,
      anon_sym_LF,
  [848] = 1,
    ACTIONS(235), 1,
      anon_sym_LF,
  [852] = 1,
    ACTIONS(33), 1,
      anon_sym_RBRACE,
  [856] = 1,
    ACTIONS(237), 1,
      anon_sym_SEMI,
  [860] = 1,
    ACTIONS(239), 1,
      sym_identifier,
  [864] = 1,
    ACTIONS(139), 1,
      anon_sym_LPAREN,
  [868] = 1,
    ACTIONS(241), 1,
      anon_sym_LF,
  [872] = 1,
    ACTIONS(243), 1,
      anon_sym_LF,
  [876] = 1,
    ACTIONS(245), 1,
      anon_sym_RBRACE,
  [880] = 1,
    ACTIONS(247), 1,
      anon_sym_SEMI,
  [884] = 1,
    ACTIONS(249), 1,
      anon_sym_DOT,
  [888] = 1,
    ACTIONS(251), 1,
      anon_sym_LF,
  [892] = 1,
    ACTIONS(253), 1,
      anon_sym_DOT,
  [896] = 1,
    ACTIONS(255), 1,
      anon_sym_RBRACE,
  [900] = 1,
    ACTIONS(257), 1,
      anon_sym_LF,
  [904] = 1,
    ACTIONS(259), 1,
      anon_sym_RBRACK,
  [908] = 1,
    ACTIONS(261), 1,
      anon_sym_LF,
  [912] = 1,
    ACTIONS(263), 1,
      anon_sym_LF,
  [916] = 1,
    ACTIONS(265), 1,
      anon_sym_LF,
  [920] = 1,
    ACTIONS(267), 1,
      anon_sym_SQUOTE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 26,
  [SMALL_STATE(4)] = 56,
  [SMALL_STATE(5)] = 86,
  [SMALL_STATE(6)] = 116,
  [SMALL_STATE(7)] = 146,
  [SMALL_STATE(8)] = 170,
  [SMALL_STATE(9)] = 194,
  [SMALL_STATE(10)] = 216,
  [SMALL_STATE(11)] = 232,
  [SMALL_STATE(12)] = 246,
  [SMALL_STATE(13)] = 260,
  [SMALL_STATE(14)] = 279,
  [SMALL_STATE(15)] = 298,
  [SMALL_STATE(16)] = 308,
  [SMALL_STATE(17)] = 330,
  [SMALL_STATE(18)] = 352,
  [SMALL_STATE(19)] = 366,
  [SMALL_STATE(20)] = 375,
  [SMALL_STATE(21)] = 392,
  [SMALL_STATE(22)] = 409,
  [SMALL_STATE(23)] = 422,
  [SMALL_STATE(24)] = 431,
  [SMALL_STATE(25)] = 444,
  [SMALL_STATE(26)] = 453,
  [SMALL_STATE(27)] = 466,
  [SMALL_STATE(28)] = 483,
  [SMALL_STATE(29)] = 500,
  [SMALL_STATE(30)] = 517,
  [SMALL_STATE(31)] = 533,
  [SMALL_STATE(32)] = 549,
  [SMALL_STATE(33)] = 565,
  [SMALL_STATE(34)] = 578,
  [SMALL_STATE(35)] = 585,
  [SMALL_STATE(36)] = 598,
  [SMALL_STATE(37)] = 607,
  [SMALL_STATE(38)] = 616,
  [SMALL_STATE(39)] = 626,
  [SMALL_STATE(40)] = 636,
  [SMALL_STATE(41)] = 642,
  [SMALL_STATE(42)] = 650,
  [SMALL_STATE(43)] = 656,
  [SMALL_STATE(44)] = 662,
  [SMALL_STATE(45)] = 668,
  [SMALL_STATE(46)] = 674,
  [SMALL_STATE(47)] = 680,
  [SMALL_STATE(48)] = 687,
  [SMALL_STATE(49)] = 692,
  [SMALL_STATE(50)] = 699,
  [SMALL_STATE(51)] = 704,
  [SMALL_STATE(52)] = 711,
  [SMALL_STATE(53)] = 718,
  [SMALL_STATE(54)] = 725,
  [SMALL_STATE(55)] = 732,
  [SMALL_STATE(56)] = 739,
  [SMALL_STATE(57)] = 744,
  [SMALL_STATE(58)] = 751,
  [SMALL_STATE(59)] = 756,
  [SMALL_STATE(60)] = 763,
  [SMALL_STATE(61)] = 768,
  [SMALL_STATE(62)] = 775,
  [SMALL_STATE(63)] = 780,
  [SMALL_STATE(64)] = 784,
  [SMALL_STATE(65)] = 788,
  [SMALL_STATE(66)] = 792,
  [SMALL_STATE(67)] = 796,
  [SMALL_STATE(68)] = 800,
  [SMALL_STATE(69)] = 804,
  [SMALL_STATE(70)] = 808,
  [SMALL_STATE(71)] = 812,
  [SMALL_STATE(72)] = 816,
  [SMALL_STATE(73)] = 820,
  [SMALL_STATE(74)] = 824,
  [SMALL_STATE(75)] = 828,
  [SMALL_STATE(76)] = 832,
  [SMALL_STATE(77)] = 836,
  [SMALL_STATE(78)] = 840,
  [SMALL_STATE(79)] = 844,
  [SMALL_STATE(80)] = 848,
  [SMALL_STATE(81)] = 852,
  [SMALL_STATE(82)] = 856,
  [SMALL_STATE(83)] = 860,
  [SMALL_STATE(84)] = 864,
  [SMALL_STATE(85)] = 868,
  [SMALL_STATE(86)] = 872,
  [SMALL_STATE(87)] = 876,
  [SMALL_STATE(88)] = 880,
  [SMALL_STATE(89)] = 884,
  [SMALL_STATE(90)] = 888,
  [SMALL_STATE(91)] = 892,
  [SMALL_STATE(92)] = 896,
  [SMALL_STATE(93)] = 900,
  [SMALL_STATE(94)] = 904,
  [SMALL_STATE(95)] = 908,
  [SMALL_STATE(96)] = 912,
  [SMALL_STATE(97)] = 916,
  [SMALL_STATE(98)] = 920,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace_part, 3, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_path, 3, 0, 1),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_path, 3, 0, 1),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_getter, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_getter, 2, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_getter, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_getter, 3, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_simple_type, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__array_modifier, 2, 0, 0),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__array_modifier, 2, 0, 0), SHIFT_REPEAT(51),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__array_modifier, 3, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(91),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generic_type, 4, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__ref_modifier, 2, 0, 0),
  [93] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__ref_modifier, 2, 0, 0), SHIFT_REPEAT(26),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [104] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [113] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [116] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_literal_repeat1, 2, 0, 0), SHIFT_REPEAT(29),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_accessibility, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal_content, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal_content, 1, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_signature, 3, 0, 2),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_signature, 4, 0, 4),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_default_value, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg, 2, 0, 6),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_negative_literal, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_char_literal, 3, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 3, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg, 4, 0, 6),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_definition, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [175] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_list, 3, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_type_list, 1, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_signature, 4, 0, 3),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_list, 3, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_list, 1, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_signature, 6, 0, 4),
  [213] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_signature, 1, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_signature, 6, 0, 5),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setter, 2, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_signature, 6, 0, 2),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_signature, 5, 0, 2),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_signature, 7, 0, 7),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_signature, 7, 0, 4),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_signature, 7, 0, 2),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_namespace_part, 1, 0, 0),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_setter, 3, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_signature, 5, 0, 2),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_enum_signature, 6, 0, 3),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_signature, 8, 0, 4),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method_signature, 6, 0, 4),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_noogle(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
    .name = "noogle",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
